#!/bin/bash

#SBATCH --nodes=1                    
#SBATCH --ntasks-per-node=56
#SBATCH --partition test # short
#SBATCH --time=0:30:00
#SBATCH --job-name=LiF
#SBATCH --export=ALL
#SBATCH --output=myjob_%j.stdout

#SBATCH --mail-user=rdelgrande@ucmerced.edu
#SBATCH --mail-type=ALL

export OMP_NUM_THREADS=1

module load berkeleygw

cd GWBSE

cd 1-epsilon/
srun epsilon.cplx.x &> epsilon.out
cd ../

cd 2-sigma/
srun sigma.cplx.x &> sigma.out 
cd ../

cd 3-kernel/
srun kernel.cplx.x &> kernel.out 
cd ../

cd 4-absorption/
srun absorption.cplx.x &> absorption.out 
cd ../
